### ISSUE TITLE
No interface definition written if type is set to "interface"

### ISSUE THREAD

**Issue by kwbr** [debops/ansible-ifupdown#2]
Given a configuration like this:

```
ifupdown_interfaces:
  - iface: 'eth1'
    type: 'interface'
    inet: 'static'
    options: |
      address 10.10.22.123
      netmask 255.255.255.0
```

no configuration file is written. The template interfaces.j2 only writes a configuration if the item.type is undefined:

```
{% if (item.type is undefined and item.iface in ansible_interfaces) or (item.force is defined and item.force) %}
```
