### ISSUE TITLE
All instructions are skipping

### ISSUE THREAD

**Issue by atrauzzi** [debops/ansible-ifupdown#22]
I strongly suspect this is going to be a beginner issue, but I'm having a difficult time understanding why ansible isn't applying any actions I've configured from this role:

(I'm running ansible in pull-mode, so that's why I'm using localhost)

```

---
-
  hosts: localhost
  roles:
    - role: debops.ifupdown
      ifupdown_interfaces:
        -
          iface: wlan0
          inet: static
          auto: True
          options:
            address: 192.168.1.1
            netmask: 255.255.255.0
```

This results in the following output:

```
TASK: [debops.ifupdown | Check if default configuration is static] ************ 
skipping: [localhost]

TASK: [debops.ifupdown | Enable static default configuration if detected] ***** 
skipping: [localhost]

TASK: [debops.ifupdown | Divert original /etc/network/interfaces] ************* 
skipping: [localhost]

TASK: [debops.ifupdown | Create /etc/network/interfaces] ********************** 
skipping: [localhost]

TASK: [debops.ifupdown | Check if Network Manager is installed] *************** 
skipping: [localhost]

TASK: [debops.ifupdown | Enable Network Manager support if installed] ********* 
skipping: [localhost]

TASK: [debops.ifupdown | Load default interface configuration] **************** 
skipping: [localhost] => (item=/etc/ansible/roles/debops.ifupdown/vars/default.yml)

TASK: [debops.ifupdown | Prepare interface configuration if not defined] ****** 
skipping: [localhost]

TASK: [debops.ifupdown | Prepare interface configuration via dependency if defined] *** 
skipping: [localhost]

TASK: [debops.ifupdown | Add package dependencies for full interface declaration functionality] *** 
skipping: [localhost]

TASK: [debops.ifupdown | Create /etc/network/interfaces.d directory] ********** 
skipping: [localhost]

TASK: [debops.ifupdown | Delete interface configuration if requested] ********* 
skipping: [localhost] => (item={'auto': True, 'iface': 'wlan0', 'options': {'netmask': '255.255.255.0', 'address': '192.168.1.1'}, 'inet': 'static'})

TASK: [debops.ifupdown | Generate interface configuration] ******************** 
skipping: [localhost] => (item={'auto': True, 'iface': 'wlan0', 'options': {'netmask': '255.255.255.0', 'address': '192.168.1.1'}, 'inet': 'static'})

TASK: [debops.ifupdown | Reconfigure interfaces] ****************************** 
skipping: [localhost] => (item={u'skipped': True, u'changed': False})
```

As I mentioned, it's entirely likely I'm missing something, but would definitely appreciate any pointers or obvious-solutions! :D

**Comment by drybjed** [comment]
@atrauzzi I think that the format you used is wrong, try this instead:
```
---
- hosts: localhost
  sudo: True
  roles:
    - role: debops.ifupdown
      ifupdown_interfaces:
        - iface: wlan0
          inet: static
          auto: True
          options: |
            address: 192.168.1.1
            netmask: 255.255.255.0
```
Also, is `wlan0` present in `ansible_interfaces`?

**Comment by atrauzzi** [comment]
Would you happen to know where I check `ansible_interfaces`?

Also, I have the following and it's still skipping:

```
---
- 
  hosts: localhost
  roles:
    - role: debops.ifupdown
      ifupdown_interfaces:
        - iface: wlan0
          inet: static
          auto: True
          options:
            address: 192.168.1.1
            netmask: 255.255.255.0

  tasks:

    # Set up hostapd
    apt: name=hostapd
```
