### ISSUE TITLE
dhclient left dangling

### ISSUE THREAD

**Issue by sxpert** [debops/ansible-ifupdown#47]
start point is pxe-installed ubuntu with eth0 configured with dhcp
when configuring the following

```
  - role: 'debops.ifupdown'
    ifupdown_ignore_cap12s: True
    ifupdown_ignore_static: True
    ifupdown_interfaces:
      - iface: 'eth0'
        type: 'interface'
        inet: 'static'
        addresses: '{{ machine.public_ip }}'
        gateway: '{{ bridge.ip_addr|ipaddr("address") }}'
        options: 'dns-nameservers {{ machine.priv_ip|ipaddr("address") }}'
      - iface: 'eth1'
        type: 'interface'
        inet: 'static'
        addresses: '{{ machine.priv_ip }}'
```

this process is left dangling :

```
dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
```

it should probably be killed by the bash script
