### ISSUE TITLE
Failure when running without systemd

### ISSUE THREAD

**Issue by dop251** [debops/ansible-ifupdown#62]
I'm running Jessie without systemd. Trying to run ifupdown gives the following error:

/root/.ansible/tmp/ansible-tmp-1481831976.28-70132869526585/ifupdown-reconfigure-interfaces: line 323: systemd_ifup_instances: unbound variable

**Comment by drybjed** [comment]
Thanks for the heads up. Do you know if this issue shows up on Debian Wheezy as well? I will check this out on a system without `systemd` init ASAP.

**Comment by dop251** [comment]
It works fine on wheezy

**Comment by drybjed** [comment]
As I thought. Any good guide to switch the init system on Jessie? Which one are you using, btw?

**Comment by dop251** [comment]
I use the following ansible task:

```
- name: install sysV
  apt: name={{item}} state=latest
  with_items:
  - sysvinit-core
  - sysvinit
  - sysvinit-utils

- name: restart machine
  command: shutdown -r now "Ansible updates triggered"
  # command: /bin/true
  async: 0
  poll: 0
  ignore_errors: true

- name: waiting for server to shutdown
  local_action: wait_for host={{ inventory_hostname }} port=22
                state=stopped
  sudo: false

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} port=22
                state=started
  sudo: false

- name: purge systemd
  shell: "{{ item }}"
  with_items:
  - apt-get remove -y --purge --auto-remove systemd
  - |
    echo 'Package: systemd\nPin: origin ""\nPin-Priority: -1' > /etc/apt/preferences.d/systemd
  - |
    echo '\n\nPackage: *systemd*\nPin: origin ""\nPin-Priority: -1' >> /etc/apt/preferences.d/systemd
```

Note, when I re-run it on a clean system I got the following error:

```
TASK [debops.ifupdown : Reload systemd services] *******************************
fatal: [178.62.106.123]: FAILED! => {"changed": false, "cmd": "systemctl daemon-reload", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
```
