### ISSUE TITLE
Setting multiple IP addresses in the same interface. Is this possible?

### ISSUE THREAD

**Issue by lchigami** [debops/ansible-ifupdown#70]
I'm trying to setup a single interface with multiple IP addresses (IP aliases).
Theoretically, the "ip" command is capable of doing this, but I'm unable to perform this using this module and Ansible.

**Comment by lchigami** [comment]
Sorry, my mistake.
I was using the wrong configuration...

**Comment by drybjed** [comment]
In case anybody else finds this issue, you can do this by specifying multiple IP addresses in the interface configuration:
```yaml
ifupdown__interfaces:
  'eth0':
    inet: 'static'
    address: [ '192.0.2.1/24', '192.0.2.2/24' ]
```
